[package]
name = "rust-slint-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
slint = "1"
image = { version = "0.24.0", default-features = false, features = [ "png" ] }
