// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { HorizontalBox, VerticalBox, ListView, StandardListView, GroupBox } from "std-widgets.slint";
import { GallerySettings } from "../gallery_settings.slint";
import { Page } from "page.slint";

// 对外导出全局单例（可与 Rust 代码直接交互）
export global ListViewPageAdapter  {
    // StandardListView model (in StandardListViewItem): The model
    in property <[StandardListViewItem]> list_data: [
        {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
        {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
        {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
        {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
        {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
        {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
        {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
    ];
}

// ListView 的页面，展示 ListView 构建的 UI 页面
export component ListViewPage inherits Page {
    title: "ListView";
    description: "ListViews can be used to display a list of elements. The StandardListBox is like the default ListView just with a default text based definition of the visual items. Both can be imported from \"std-widgets.slint\"";
    // 横向 Box 组件：包含两组ListView
    HorizontalBox {   
        vertical-stretch: 1;
        // 第一个列表：ListView
        GroupBox {  
            title: "ListView";

            ListView {  
                vertical-stretch: 0;
                // 布局是索引为 0-11 的 HorizontalBox，当然可以使用其他组件
                for i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] : HorizontalBox {
                   Image {
                        width: 24px;
                        source: @image-url("../../thumbsup.png");
                   }
                   Text {
                        text: "Item " + i;
                   }
                }
            }
        }
       // 第二个列表：StandardListView
        GroupBox {  
            title: "StandardListView";
            vertical-stretch: 0;

            StandardListView {
                // model方案1: 直接写死数组
                // model: [
                //     {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                //     {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                //     {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                //     {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                //     {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                //     {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                //     {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                // ];
                // model方案2: 可与 Rust 代码动态交互的数据
                model: ListViewPageAdapter.list-data;
            }
        }
    }
}
