// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

// 导入各个Page文件
import { AboutPage } from "about_page.slint";
import { ControlsPage } from "controls_page.slint";
import { ListViewPage } from "list_view_page.slint";
import { TableViewPage, TableViewPageAdapter } from "table_view_page.slint";
import { TextEditPage } from "text_edit_page.slint";

// 导出各个Page
export { AboutPage, ControlsPage, ListViewPage, TextEditPage, TableViewPage, TableViewPageAdapter }