// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { HorizontalBox, VerticalBox, StandardTableView, GroupBox} from "std-widgets.slint";
import { GallerySettings } from "../gallery_settings.slint";
import { Page } from "page.slint";

// 对外导出全局单例（可与 Rust 代码直接交互）
export global TableViewPageAdapter  {
    callback sort_ascending(int); // 正序回调
    callback sort_descending(int); // 逆序回调
    // StandardTableView rows数据（即 List Data），数据是 4行 n 列的一个矩阵
    in property <[[StandardListViewItem]]> row_data: [
        [ { text: "Item 1.1" }, { text: "Item 1.2" }, { text: "Item 1.3" }, { text: "Item 1.4" }, ],
        [ { text: "Item 2.1" }, { text: "Item 2.2" }, { text: "Item 2.3" }, { text: "Item 2.4" }, ],
        [ { text: "Item 3.1" }, { text: "Item 3.2" }, { text: "Item 3.3" }, { text: "Item 3.4" }, ],
        [ { text: "Item 4.1" }, { text: "Item 4.2" }, { text: "Item 4.3" }, { text: "Item 4.4" }, ],
        [ { text: "Item 5.1" }, { text: "Item 5.2" }, { text: "Item 5.3" }, { text: "Item 5.4" }, ],
        [ { text: "Item 6.1" }, { text: "Item 6.2" }, { text: "Item 6.3" }, { text: "Item 6.4" }, ],
    ];
    // StandardTableView columns数据（即 List Header）
    in property <[TableColumn]> column_data: [
        { title: "Header 1" },
        { title: "Header 2" },
        { title: "Header 3" },
        { title: "Header 4" },
    ];
}

// TableViewPage 页面，展示一个StandardTableView
export component TableViewPage inherits Page {
    title: "TableView";
    description: "StandardTableView can be used to display a list of text elements in columns and rows. It can be imported from \"std-widgets.slint\"";

    HorizontalBox {
        vertical-stretch: 1;

        GroupBox {
            title: "StandardTableView";
            vertical-stretch: 0;

            StandardTableView {
                sort-ascending(index) => { // 正次排序
                    TableViewPageAdapter.sort_ascending(index);
                }

                sort-descending(index) => { // 逆序排序
                    TableViewPageAdapter.sort-descending(index);
                }
                // columns: [
                //     { title: "Header 1" },
                //     { title: "Header 2" },
                //     { title: "Header 3" },
                //     { title: "Header 4" },
                // ];

                // Table columns
                columns: TableViewPageAdapter.column_data;
                // Table rows
                rows: TableViewPageAdapter.row_data;
            }
        }
    }
}
