[package]
name = "android-calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
slint = "1.5.0"
i-slint-backend-android-activity = { version = "=1.5.0", features = ["native-activity"] }