import { TabPageA } from "./ui/page_a.slint";
import { TabPageB } from "./ui/page_b.slint";
import { SliderPage } from "./ui/page_slider.slint";

import { Button } from "std-widgets.slint";
// 创建自己的自定义选项卡小部件Tabs
export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    in-out property <int> active-tab;
    VerticalLayout {
        tab_bar := HorizontalLayout {
            spacing: 3px;
            Button {
                text: "Tab1";
                clicked => { root.active-tab = 0; }
            }
            Button {
                text: "Tab2";
                clicked => { root.active-tab = 1; }
            }
            Button {
                text: "Slider";
                clicked => { root.active-tab = 2; }
            }
        }
        Rectangle {
            clip: true;
            TabPageA {
                // background: red;
                x: root.active-tab == 0 ? 0 : root.active-tab < 0 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
            }
            TabPageB {
                background: blue;
                x: root.active-tab == 1 ? 0 : root.active-tab < 1 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
            }
            SliderPage {
                background: green;
                x: root.active-tab == 2 ? 0 : root.active-tab < 2 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
            }
        }
    }
}