import { HorizontalBox, VerticalBox } from "std-widgets.slint";

// Page的模版组件，提供统一样式的页面布局以供选择。
export component Page inherits VerticalBox {
    in property<string> title: "title";
    alignment: start;
    
    HorizontalBox { 
       // spacing: 5px;
       // padding-left: 5px;
       // padding-right: 5px;
       // alignment: start;
        
        Text {  
            font-size: 20px;
            text <=> root.title;
        }
    }

    @children
}