import {GroupBox, HorizontalBox, StandardListView, ListView} from "std-widgets.slint";

export component TabPageB inherits Rectangle {
    HorizontalBox {   
        vertical-stretch: 1;
        alignment: start;
        GroupBox {  
            title: "ListView";
            ListView {  
                vertical-stretch: 0;
                for i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] : HorizontalBox {
                   Image {
                        width: 24px;
                        source: @image-url("../icons/at.png");
                   }
                   Text {
                        text: "Item " + i;
                   }
                }
            }
        }

        GroupBox {  
            title: "StandardListView";
            vertical-stretch: 0;

            StandardListView {
                model: [
                    {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                    {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                    {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                    {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                    {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                    {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                    {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                ];
            }
        }
    }
}