import { CheckBox, GridBox, ListView, ScrollView, VerticalBox } from "std-widgets.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";

    VerticalBox { 
        // spacing: 5px;
       padding-left: 25px;
       padding-right: 25px;
       alignment: start;
        
        Text {  
            font-size: 20px;
            text <=> root.title;
        }
    }

    @children
}